// Helper function to generate October dates
const generateOctoberDate = (dayOffset: number) => {
  const date = new Date(2024, 9, 15) // October 15, 2024 as base date
  date.setDate(date.getDate() + dayOffset)
  return date.toLocaleDateString("es-ES", { day: "2-digit", month: "2-digit", year: "numeric" })
}

// Raw reservation data structure
export const rawReservations = [
  // 25 reservations for October 15th (today)
  { id: "3001", locator: "oct001", name: "Ana García", email: "ana@garcia.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Standard', aci: "2/0/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: false },
  { id: "3002", locator: "oct002", name: "Carlos López", email: "carlos@lopez.com", checkIn: generateOctoberDate(0), nights: 4, roomType: 'Superior', aci: "1/1/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3003", locator: "oct003", name: "María Rodríguez", email: "maria@rodriguez.com", checkIn: generateOctoberDate(0), nights: 2, roomType: 'Deluxe', aci: "2/0/0", status: "New", extrasCount: 3, hasExtras: true, hasHotelverseRequest: false },
  { id: "3004", locator: "oct004", name: "José Martínez", email: "jose@martinez.com", checkIn: generateOctoberDate(0), nights: 5, roomType: 'Suite', aci: "3/1/0", status: "New", extrasCount: 4, hasExtras: true, hasHotelverseRequest: true },
  { id: "3005", locator: "oct005", name: "Laura Sánchez", email: "laura@sanchez.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Presidential Suite', aci: "2/0/0", status: "New", extrasCount: 4, hasExtras: true, hasHotelverseRequest: false },
  { id: "3006", locator: "oct006", name: "David González", email: "david@gonzalez.com", checkIn: generateOctoberDate(0), nights: 4, roomType: 'Standard', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3007", locator: "oct007", name: "Carmen Fernández", email: "carmen@fernandez.com", checkIn: generateOctoberDate(0), nights: 2, roomType: 'Superior', aci: "2/1/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: false },
  { id: "3008", locator: "oct008", name: "Miguel Pérez", email: "miguel@perez.com", checkIn: generateOctoberDate(0), nights: 6, roomType: 'Deluxe', aci: "2/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3009", locator: "oct009", name: "Isabel Ruiz", email: "isabel@ruiz.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Suite', aci: "1/1/0", status: "New", extrasCount: 3, hasExtras: true, hasHotelverseRequest: false },
  { id: "3010", locator: "oct010", name: "Antonio Jiménez", email: "antonio@jimenez.com", checkIn: generateOctoberDate(0), nights: 4, roomType: 'Presidential Suite', aci: "3/0/1", status: "New", extrasCount: 4, hasExtras: true, hasHotelverseRequest: true },
  { id: "3011", locator: "oct011", name: "Pilar Moreno", email: "pilar@moreno.com", checkIn: generateOctoberDate(0), nights: 2, roomType: 'Standard', aci: "2/0/0", status: "New", extrasCount: 3, hasExtras: true, hasHotelverseRequest: false },
  { id: "3012", locator: "oct012", name: "Francisco Álvarez", email: "francisco@alvarez.com", checkIn: generateOctoberDate(0), nights: 5, roomType: 'Superior', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3013", locator: "oct013", name: "Rosa Romero", email: "rosa@romero.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Deluxe', aci: "2/1/0", status: "New", extrasCount: 4, hasExtras: true, hasHotelverseRequest: false },
  { id: "3014", locator: "oct014", name: "Manuel Torres", email: "manuel@torres.com", checkIn: generateOctoberDate(0), nights: 4, roomType: 'Suite', aci: "2/0/0", status: "New", extrasCount: 3, hasExtras: true, hasHotelverseRequest: true },
  { id: "3015", locator: "oct015", name: "Dolores Vázquez", email: "dolores@vazquez.com", checkIn: generateOctoberDate(0), nights: 2, roomType: 'Presidential Suite', aci: "1/1/0", status: "New", extrasCount: 3, hasExtras: true, hasHotelverseRequest: false },
  { id: "3016", locator: "oct016", name: "Jesús Ramos", email: "jesus@ramos.com", checkIn: generateOctoberDate(0), nights: 6, roomType: 'Standard', aci: "3/1/0", status: "New", extrasCount: 4, hasExtras: true, hasHotelverseRequest: true },
  { id: "3017", locator: "oct017", name: "Amparo Castro", email: "amparo@castro.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Superior', aci: "2/0/0", status: "New", extrasCount: 3, hasExtras: true, hasHotelverseRequest: false },
  { id: "3018", locator: "oct018", name: "Ángel Ortega", email: "angel@ortega.com", checkIn: generateOctoberDate(0), nights: 4, roomType: 'Deluxe', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3019", locator: "oct019", name: "Remedios Delgado", email: "remedios@delgado.com", checkIn: generateOctoberDate(0), nights: 2, roomType: 'Suite', aci: "2/1/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: false },
  { id: "3020", locator: "oct020", name: "Fernando Herrera", email: "fernando@herrera.com", checkIn: generateOctoberDate(0), nights: 5, roomType: 'Presidential Suite', aci: "2/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3021", locator: "oct021", name: "Encarnación Molina", email: "encarnacion@molina.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Standard', aci: "1/1/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: false },
  { id: "3022", locator: "oct022", name: "Rafael Vargas", email: "rafael@vargas.com", checkIn: generateOctoberDate(0), nights: 4, roomType: 'Superior', aci: "3/0/1", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3023", locator: "oct023", name: "Josefa Iglesias", email: "josefa@iglesias.com", checkIn: generateOctoberDate(0), nights: 2, roomType: 'Deluxe', aci: "2/0/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: false },
  { id: "3024", locator: "oct024", name: "Enrique Medina", email: "enrique@medina.com", checkIn: generateOctoberDate(0), nights: 6, roomType: 'Suite', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: true },
  { id: "3025", locator: "oct025", name: "Concepción Garrido", email: "concepcion@garrido.com", checkIn: generateOctoberDate(0), nights: 3, roomType: 'Presidential Suite', aci: "2/1/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: false },

  // 25 reservations for October 16th (tomorrow)
  { id: "4001", locator: "oct101", name: "Pablo Serrano", email: "pablo@serrano.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Standard', aci: "2/0/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
  { id: "4002", locator: "oct102", name: "Mercedes Peña", email: "mercedes@pena.com", checkIn: generateOctoberDate(1), nights: 4, roomType: 'Superior', aci: "1/1/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4003", locator: "oct103", name: "Andrés Cruz", email: "andres@cruz.com", checkIn: generateOctoberDate(1), nights: 2, roomType: 'Deluxe', aci: "2/0/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: true },
  { id: "4004", locator: "oct104", name: "Esperanza Flores", email: "esperanza@flores.com", checkIn: generateOctoberDate(1), nights: 5, roomType: 'Suite', aci: "3/1/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4005", locator: "oct105", name: "Ramón Herrero", email: "ramon@herrero.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Presidential Suite', aci: "2/0/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
  { id: "4006", locator: "oct106", name: "Milagros Cabrera", email: "milagros@cabrera.com", checkIn: generateOctoberDate(1), nights: 4, roomType: 'Standard', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4007", locator: "oct107", name: "Sebastián Bernal", email: "sebastian@bernal.com", checkIn: generateOctoberDate(1), nights: 2, roomType: 'Superior', aci: "2/1/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: true },
  { id: "4008", locator: "oct108", name: "Asunción León", email: "asuncion@leon.com", checkIn: generateOctoberDate(1), nights: 6, roomType: 'Deluxe', aci: "2/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4009", locator: "oct109", name: "Emilio Blanco", email: "emilio@blanco.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Suite', aci: "1/1/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
  { id: "4010", locator: "oct110", name: "Rosario Suárez", email: "rosario@suarez.com", checkIn: generateOctoberDate(1), nights: 4, roomType: 'Presidential Suite', aci: "3/0/1", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4011", locator: "oct111", name: "Gregorio Vega", email: "gregorio@vega.com", checkIn: generateOctoberDate(1), nights: 2, roomType: 'Standard', aci: "2/0/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: true },
  { id: "4012", locator: "oct112", name: "Purificación Morales", email: "purificacion@morales.com", checkIn: generateOctoberDate(1), nights: 5, roomType: 'Superior', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4013", locator: "oct113", name: "Patricio Santos", email: "patricio@santos.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Deluxe', aci: "2/1/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
  { id: "4014", locator: "oct114", name: "Inmaculada Pastor", email: "inmaculada@pastor.com", checkIn: generateOctoberDate(1), nights: 4, roomType: 'Suite', aci: "2/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4015", locator: "oct115", name: "Evaristo Lorenzo", email: "evaristo@lorenzo.com", checkIn: generateOctoberDate(1), nights: 2, roomType: 'Presidential Suite', aci: "1/1/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: true },
  { id: "4016", locator: "oct116", name: "Nieves Pascual", email: "nieves@pascual.com", checkIn: generateOctoberDate(1), nights: 6, roomType: 'Standard', aci: "3/1/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4017", locator: "oct117", name: "Celestino Soler", email: "celestino@soler.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Superior', aci: "2/0/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
  { id: "4018", locator: "oct118", name: "Visitación Aguilar", email: "visitacion@aguilar.com", checkIn: generateOctoberDate(1), nights: 4, roomType: 'Deluxe', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4019", locator: "oct119", name: "Teodoro Lozano", email: "teodoro@lozano.com", checkIn: generateOctoberDate(1), nights: 2, roomType: 'Suite', aci: "2/1/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: true },
  { id: "4020", locator: "oct120", name: "Natividad Cano", email: "natividad@cano.com", checkIn: generateOctoberDate(1), nights: 5, roomType: 'Presidential Suite', aci: "2/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4021", locator: "oct121", name: "Leopoldo Prieto", email: "leopoldo@prieto.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Standard', aci: "1/1/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
  { id: "4022", locator: "oct122", name: "Presentación Calvo", email: "presentacion@calvo.com", checkIn: generateOctoberDate(1), nights: 4, roomType: 'Superior', aci: "3/0/1", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4023", locator: "oct123", name: "Casimiro Campos", email: "casimiro@campos.com", checkIn: generateOctoberDate(1), nights: 2, roomType: 'Deluxe', aci: "2/0/0", status: "New", extrasCount: 1, hasExtras: true, hasHotelverseRequest: true },
  { id: "4024", locator: "oct124", name: "Angustias Reyes", email: "angustias@reyes.com", checkIn: generateOctoberDate(1), nights: 6, roomType: 'Suite', aci: "1/0/0", status: "New", extrasCount: 0, hasExtras: false, hasHotelverseRequest: false },
  { id: "4025", locator: "oct125", name: "Saturnino Vila", email: "saturnino@vila.com", checkIn: generateOctoberDate(1), nights: 3, roomType: 'Presidential Suite', aci: "2/1/0", status: "New", extrasCount: 2, hasExtras: true, hasHotelverseRequest: true },
]